# Generated by Django 3.0.5 on 2022-10-08 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0003_auto_20221007_2226'),
        ('universidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='creditos',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Creditos'),
        ),
        migrations.AddField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docente.Docente', verbose_name='Docente'),
        ),
    ]
