# Generated by Django 3.0.5 on 2022-10-08 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0002_auto_20221007_2226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['nombre'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelTable(
            name='curso',
            table='tbl_cursos',
        ),
    ]
