# Generated by Django 3.0.5 on 2022-10-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0002_auto_20221007_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='fecha_nacimiento',
            field=models.DateField(null=True, verbose_name='Fecha nacimiento'),
        ),
    ]
