# Generated by Django 3.0.5 on 2022-10-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('punteo', models.IntegerField(verbose_name='Punteo')),
                ('fechaVencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
            ],
        ),
    ]
