# Generated by Django 3.0.5 on 2022-10-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0002_auto_20221001_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fechaVencimiento',
            field=models.DateTimeField(verbose_name='Fecha de Vencimiento'),
        ),
    ]
