# Generated by Django 3.0.5 on 2022-10-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0005_auto_20221001_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fechaVencimiento',
            field=models.DateField(verbose_name='Fecha de Vencimiento'),
        ),
    ]
