# Generated by Django 3.0.5 on 2022-10-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0008_auto_20221007_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
    ]
