# Generated by Django 3.0.5 on 2022-10-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0009_tarea_fechacreacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fechaCreacion',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
    ]
